### ISSUE TITLE
Make yellow clues prefer to match on the same word.

### ISSUE THREAD

**Issue by flackr** [flackr/crosswordle#11]
Currently if you have the same letter in an incorrect position in both of your guess words and there is only one in the answer, the horizontal word's letter will get the yellow clue as it is evaluated first. However, this is just an implementation detail, and it would be nicer if the yellow clue was given to the word containing that letter. E.g. assuming you guessed

```
  W
CROSS
  R
  D
```
If there was only an R in the second word, it should give the yellow clue to the R in WORD, rather than the one in CROSS.

**Comment by HoCoMrDude** [comment]
Similar issue: if there is a single instance of a given letter across both words, and the player guesses two words that each contain this letter once, both instances show as yellow, leading to an incorrect inference that the word pair contains two of this letter.
