### ISSUE TITLE
Cross letter coloring seems non-intuitive

### ISSUE THREAD

**Issue by gosko** [flackr/crosswordle#13]
When the cross letter is correct but in the wrong position, coloring it yellow in both words when it only exists once seems non-intuitive (or at least it threw me off for a while today). I feel like it would make more sense to treat the cross letter as two independent guesses. The current behavior is clearly documented on the help page so this isn't a bug report, just a suggestion. Thanks for making Crosswordle!

**Comment by flackr** [comment]
Thanks for filing the issue. This is something that I've been thinking about along with making the same letter in both words in other positions more valuable (#11): https://twitter.com/flackrw/status/1489261804291170304 . I think it would be a reasonable change.

In the meantime though, I've landed a dynamic keyboard feature #12 which would let you know after you type one of the letter that there isn't another one - so hopefully this helps keep things clear for the current behavior.

**Comment by gosko** [comment]
Thanks. Dynamic keyboard is very helpful!
