### ISSUE TITLE
Found letter colouring on keyboard hard to distinguish

### ISSUE THREAD

**Issue by briandealwis** [flackr/crosswordle#26]
The yellowish colour used for found letters on the keyboard is very hard to distinguish from that used for untried letters:

![A353D534-6443-498E-8C6C-F63730F95837](https://user-images.githubusercontent.com/202851/155125410-f612301f-6de5-4170-9ae0-44b23859f385.jpeg)

**Comment by briandealwis** [comment]
It doesn’t look so difficult here with the daytime colour scheme, but at night, with low brightness, it’s much harder to see the difference.

This is on iOS.

**Comment by flackr** [comment]
Any recommendations? Would just brightening up the yellow a bit help?

**Comment by briandealwis** [comment]
Yes brightening the yellow would make a big difference, I think. The key colour in the above looks to have  a bit of a greenish cast.

I meant to take a picture of the Wordle keyboard for comparison, but I got green for every letter today🤦
