### ISSUE TITLE
22nd Dec cannot be solved.One of the words Sxxxa is the only solution but isnt allowed.

### ISSUE THREAD

**Issue by LynneAllister** [flackr/crosswordle#32]
See above.

**Comment by flackr** [comment]
Thanks for the report, fixing!

**Comment by flackr** [comment]
Should accept it now though you may have to force reload the page (i.e. hold shift and refresh or pull to refresh) before it does, sorry about the issue.

**Comment by LynneAllister** [comment]
Thanks Robert.
My partner and I love this puzzle,although sometimes I hate it too!,😄


Dymocks Rouse Hill
Shop GR023 Rouse Hill Town Centre
10-14 Market Lane
Rouse Hill 2155
02 88833055
***@***.***

[1506415101543_Untitled2.jpg]
________________________________

**Comment by josouth** [comment]
Not fixed yet!

**Comment by flackr** [comment]
> Not fixed yet!

I've tested it both in my development branch and on the real website.

I believe your browser may have loaded a cached older version and you need to force it to reload.

**Comment by flackr** [comment]
The underlying issue is that the word isn't in the dictionary. I'm still confused how I accidentally added a puzzle with a word that wasn't in the dictionary when the tool I wrote to add them verifies this :man_shrugging:

Thanks again for reporting it early so I could fix it before most people ran into this.

**Comment by josouth** [comment]
Hi Robert

Thanks for your quick response and quick action in fixing the issue. I didn’t realize that Santa is not in the dictionary!

Thank you,
JoSouth

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
