### ISSUE TITLE
Option to eliminate striped letter

### ISSUE THREAD

**Issue by Hi777santa** [flackr/crosswordle#36]
Hi. Would you consider providing an option to play the game without the striped letter hint? Hard mode unfortunately left the striped letters making it easier to solve.

thank you for the consideration

**Comment by flackr** [comment]
Hi there! I have already done this yesterday https://github.com/flackr/crosswordle/commit/04972b2e41d05392f92d47d4c2e73a2961b9005d 😀

If you're still seeing it today it's probably that your browser is still showing you a cached version and hasn't loaded the new code yet but you should no longer get striped clues by default unless you turn on the word-specific clues setting in the settings.

<img width="725" alt="Screenshot 2023-01-06 at 11 52 10 AM" src="https://user-images.githubusercontent.com/366761/211059152-d5467119-5f44-4056-b4e4-95215b10df7f.png">
