### ISSUE TITLE
Guessed Letters Incorrectly Highlighted in Yellow on Keyboard

### ISSUE THREAD

**Issue by Flooflez** [flackr/crosswordle#46]
A third R was highlighted in Yellow on the keyboard when there were only 2 in the whole word pair.
| ![image1](https://github.com/flackr/crosswordle/assets/97826110/20235158-b63a-474a-8220-bec7142f24a7) | ![image2](https://github.com/flackr/crosswordle/assets/97826110/f86796e5-844e-4e29-88e1-f1024bab249b) |
|-------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|

This is with Hard Mode enabled (no oranges)

**Comment by flackr** [comment]
Thanks for the report! I know what went wrong in the code, I'll get it fixed soon.
