### ISSUE TITLE
Friend plays on a tablet and letters that are correct are showing as wrong in the Xword space.

### ISSUE THREAD

**Issue by GrandizerGo** [flackr/crosswordle#47]
Today, the puzzle is "Wildest Dreams" However when she places the letter E in the crossing spot, which is correct, it is showing it as a wrong letter.
![Xword](https://github.com/user-attachments/assets/5f004aee-95f4-4abf-90fe-3a85eb8c0fea)
This has happened to her about 4 times, but I thought I would report it as a bug.

**Comment by flackr** [comment]
Thanks for the report! When this kind of issue happens you should still be able to guess it even though it's indicating the wrong thing but this specific issue should be fixed.
