### ISSUE TITLE
Firefox mobile types incorrect keys

### ISSUE THREAD

**Issue by tegendraads** [flackr/crosswordle#48]
Cannot use the keyboard on mobile. It does not respond or gives wrong letter.

**Comment by flackr** [comment]
I've tested it on both an iPhone running iOS 17.5.1 Safari and Android 14 running Chrome 127.0.6533.105 and am not seeing any issues with the keyboard. Could you give some more details? I.e. what model phone / OS / browser are you using?

**Comment by flackr** [comment]
Possibly also try a force reload of the page in case somehow your browser had loaded some old and some new files.

**Comment by flackr** [comment]
Unfortunately I have no way to reproduce the issue you encountered to diagnose and/or fix it. It may be worth checking if there are any updates for the browser / OS and also making sure to force reload the webpage (i.e. tap the reload button or pull to refresh) in case you're getting a cached version of one of the files that is incompatible with another. If it continues to happen and you have any further details let me know, but without further information there's nothing I can do. Apologies.

**Comment by tegendraads** [comment]
I use Firefox on android 11 ( huawei phone) . And I noticed this only with puzzles where the word overlaps the keyboard. It works with puzzels where there are smaller words.

**Comment by flackr** [comment]
Thanks, I am able to reproduce the issue on Firefox. Given the difference in behavior and that the keyboard is a bunch of regular clickable elements and Chrome and Safari both handle it correctly, I believe this is actually a firefox bug. I filed it over at https://bugzilla.mozilla.org/show_bug.cgi?id=1914922

**Comment by flackr** [comment]
I can probably land a workaround but I want to make sure the firefox devs have a repro case for the bug so until I put one together I'm tempted to leave it as is in the game so they can see the issue. In the meantime I think if you ensure the URL bar is visible (by scrolling up) the tap targeting seems to be correct.

**Comment by flackr** [comment]
The firefox issue has been fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1914922
