### ISSUE TITLE
Create help screen

### ISSUE THREAD

**Issue by flackr** [flackr/crosswordle#5]
Give an explanation of the clues with some examples of tricky edge cases (like yellow matching in the other word).

**Comment by zdoc01** [comment]
Friends and I are loving the game so far! Definitely think this would be helpful based on feedback. Some additional callouts I think could be useful:

* Color indicators for guesses apply to the entire board, not just the row/column in which the letter was used (think this is what you mean by "yellow matching in the other word" but just wanted to be sure)
* No limit on number of guesses allowed
* Game is similar to traditional crosswords in that the words relate to one another (unsure if you want this to be explicitly called out, or left up for interpretation to make it a little more difficult at first)
