### ISSUE TITLE
Unnecessary vertical scrollbar

### ISSUE THREAD

**Issue by dholbert** [flackr/crosswordle#6]
In Firefox as well as Chrome (on Linux in my case, but I assume all operating systems), crosswordle triggers a vertical scrollbar with just a few pixels of distance to go.

This seems to be due to the body having `height:100%` combined with the body's default nonzero margin.

Presumably you either want `body { margin: 0 }`, or you want to change the way that you make the body fill the viewport.

**Comment by dholbert** [comment]
screenshot showing the scrollbar (in Firefox):
![Screenshot from 2022-01-31 11-43-54](https://user-images.githubusercontent.com/426803/151861710-8a720139-3e9b-4dae-9f6d-1840b1d0eb86.png)

**Comment by flackr** [comment]
Thanks! Moved to defining this spacing as padding on the inner areas that need it.
